[workspace]
resolver = "2"
members = [
  "shared",
  "lambdas/create_link",
  "lambdas/get_links",
  "lambdas/visit_link",
  "lambdas/process_link_created",
  "lambdas/process_link_clicked",
  "integration-tests",
]
