[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
scraper = "0.16"
cuid2 = "0.1"
serde = "1.0"
serde_json = "1.0"
aws-sdk-dynamodb = "1.31"
reqwest = "0.13"
lambda_http = "0.11"
