[package]
name = "sqs-sendmessage"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38", features = ["macros", "rt-multi-thread"] }
aws-config = { version = "1.1", features = ["behavior-version-latest"] }
aws-sdk-sqs = "1.90.0"
serde_json = "1.0"
serde = "1.0.228"
