[package]
name = "otel-simple"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../shared" }
tokio = { version = "1.38", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0"
serde = "1.0.228"

opentelemetry = "0.31.0"
tracing = "0.1.43"